cognite:
  project: your-cognite-project
  client_name: your-client-name
  base_uri: your-cognite_base_uri
  auth_token_override: https://YOUR_IDP/oauth2/v1/token
neo4j:
  uri: neo4j+s://YOUR_INSTANCE.databases.neo4j.io
  user: neo4j_user
  password: YOUR_PASSWORD
